"""empty message

Revision ID: 1cbbf5ed4796
Revises: 3705b8ea3cdd
Create Date: 2021-04-30 11:24:45.420160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbbf5ed4796'
down_revision = '3705b8ea3cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_subscribes_name'), 'subscribes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribes_name'), table_name='subscribes')
    op.drop_table('subscribes')
    # ### end Alembic commands ###
