"""empty message

Revision ID: b4c148929329
Revises: 3e997235672d
Create Date: 2021-05-01 00:41:15.687463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c148929329'
down_revision = '3e997235672d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_comment_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    op.add_column('blogs', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_comment_id_fkey', 'blogs', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
